# frozen_string_literal: true

# info module
module Info
  def status
    magenta('Checking the Code...')
  end

  def computer_code
    magenta("\nSecret Code Generated by the Computer Player!", bold: true) + yellow('Now try to Crack!', bold: true)
  end
end
